name: CI

on:
  workflow_dispatch:
  push:
    branches: main
    paths-ignore:
      - "scripts/*"
      - "*.md"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "scripts/*"
      - "*.md"
  
permissions:
  contents: read
  actions: read
  checks: write
  
jobs:
  update-cache:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
   
  ruff-lint:
    uses: Glatzel/py-template/.github/workflows/lint.yml@main
  
  pytest:
    uses: Glatzel/py-template/.github/workflows/pytest.yml@main
    strategy:
      matrix:
        os: [windows-latest]
    with: 
      name: test
      machine: ${{matrix.os}}
      test_path: ./src
      test_args: --benchmark-max-time=0.00005 --benchmark-min-rounds=1 --benchmark-histogram=histogram/arithmetic
      cov: true
