name: CI

on:
  push:
    branches: main
    paths-ignore:
      - "scripts/*"
      - "*.md"
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
    paths-ignore:
      - "scripts/*"
      - "*.md"
  
permissions:
  contents: read
  actions: read
  checks: write
  
jobs:
  check-title:
    if: ${{ github.event_name == 'pull_request' }}
    uses: Glatzel/py-template/.github/workflows/lint-pr.yml@main

  ruff-lint:
    uses: Glatzel/py-template/.github/workflows/lint.yml@main
  
  pytest:
    uses: Glatzel/py-template/.github/workflows/pytest.yml@main
    strategy:
      matrix:
        os: [windows-latest]
    with: 
      name: test
      machine: ${{matrix.os}}
      test_path: ./src
      test_args: --benchmark-max-time=0.00005 --benchmark-min-rounds=1 --benchmark-histogram=histogram/arithmetic
      cov: true
