name: Lint Pull Requests

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-title:
    uses: Glatzel/py-template/.github/workflows/lint-pr.yml@main
