name: Lint Pull Requests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

jobs:
  check-title:
    uses: Glatzel/py-template/.github/workflows/lint-pr.yml@main
