name: lint

on:
    workflow_dispatch:
    pull_request:
      types:
        - opened
        - edited
        - synchronize
        - ready_for_review

jobs:
  ruff-lint:
    strategy:
      matrix:
        machine: [windows-latest]
    uses: Glatzel/py-template/.github/workflows/lint.yml@main
    with:
      machine: ${{matrix.machine}} 
