name: lint

on:
    workflow_dispatch:
    pull_request:
      types:
        - opened
        - edited
        - synchronize
        - ready_for_review
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ruff-lint:
    uses: Glatzel/py-template/.github/workflows/lint.yml@main
    with:
      machine: ${{matrix.machine}} 
