name: Pull Requests Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  check-title:
    uses: Glatzel/py-template/.github/workflows/lint-pr.yml@main
