name: Lint Pull Requests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

permissions:
  contents: read
  actions: read
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-title:
    uses: Glatzel/py-template/.github/workflows/lint-pr.yml@main
  ruff-lint:
    uses: Glatzel/py-template/.github/workflows/lint.yml@main
  test:
    uses: Glatzel/py-template/.github/workflows/pytest.yml@main
    with: 
      name: test
      machine: windows-latest
      test_path: ./src
      update_submodule: true
      test_args: --benchmark-max-time=0.00005 --benchmark-min-rounds=1
      cov: true
  wait-for-all:
    needs: [check-title,ruff-lint,test]
    uses: Glatzel/py-template/.github/workflows/result.yml@main
