name: Python Check

on:
  push:
    branches: main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  ruff-lint:
    uses: Glatzel/py-template/.github/workflows/lint.yml@main
  
  test:
    uses: Glatzel/py-template/.github/workflows/pytest.yml@main
    strategy:
      matrix:
        os: [windows-latest]
    with: 
      name: test
      machine: ${{matrix.os}}
      test_path: ./src
      update_submodule: true
      test_args: --benchmark-max-time=0.00005 --benchmark-min-rounds=1 --benchmark-histogram=histogram/arithmetic
      cov: true

  check-result:
    needs: [ruff-lint,test]
    runs-on: ubuntu-latest
    steps:
        - run: echo "All success."
