name: test
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "src/**.py"
      - "pixi.lock"
      - "pixi.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fft: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Submodule
        run: git submodule update --init --recursive
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false
      - name: bench
        run: |
          pixi run -e fft pytest "./src/fft" --benchmark-max-time=0.00005 --benchmark-min-rounds=1
