name: test
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bench: 
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Submodule
        run: git submodule update --init --recursive
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          run-install: false
      - name: install environment
        run: pixi install
      - name: bench
        run: pixi run pytest "./src" --benchmark-max-time=0.00005 --benchmark-min-rounds=1