name: update-lockfile
permissions: 
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 1

jobs:
  pixi-update:
    uses: Glatzel/py-template/.github/workflows/update-lockfiles.yml@main